networks:
  greenplum:
    ipam:
      config:
      - subnet: 10.188.0.0/24
        gateway: 10.188.0.1

services:
  cdw:
    image: "docker.io/qpod/greenplum"
    container_name: gpdb-cdw
    hostname: gpdb-cdw
    ports:
      - "10022:22"
      - "15432:5432"
    tty: true
    networks:
      - greenplum
    volumes:
    - /data/database/gpdb:/data/gpdb
